name: Monthly Mean Price

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Hent repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer dependencies
        run: pip install requests

      - name: Kør månedligt script
        run: python monthly_avg.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add monthly_power_prices.csv
          git commit -m "Update monthly power prices" || exit 0
          git push
